#include "sort.h"


/**
 * shell_sort - sorts array using ascending order of shel sort algorithm
 * with gap generated by knuth sequence h = 3*h+1
 * @array: the array to be sorted
 * @size: the length of the array
 */
void shell_sort(int *array, size_t size)
{
	int tmp;
	size_t h = 1, i, j;

	while (h < size / 3)
	{
		h = 3 * h + 1;
	}

	while (h >= 1)
	{
		for (i = h; i < size; i++)
		{
			for (j = i; j >= h && (array[j] < array[j - h]); j -= h)
			{
				tmp = array[j - h];
				array[j - h] = array[j];
				array[j] = tmp;
			}
		}
		print_array(array, size);
		h /= 3;
	}
}
